name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  call-build:
    uses: moclojer/moclojer/.github/workflows/build-native-image.yml@main

  release:
    needs: "call-build"
    runs-on: "ubuntu-20.04"
    environment: release
    steps:
    - uses: actions/checkout@v3
    - uses: "actions/download-artifact@v3"
      with:
        name: moclojer_bin_Linux
        path: moclojer_Linux
    - uses: "actions/download-artifact@v3"
      with:
        name: moclojer_bin_macOS
        path: moclojer_macOS
    - uses: "actions/download-artifact@v3"
      with:
        name: moclojer_jar
        path: moclojer.jar

    - uses: softprops/action-gh-release@v1
      with:
        name: ${{  github.ref_name }}
        files: |
          moclojer_Linux
          moclojer_macOS
          moclojer.jar

  call-docker:
    needs: "release"
    uses: moclojer/moclojer/.github/workflows/docker.yml@main
